name: NameService
on:
  pull_request:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      id: go
      with:
        go-version: 1.15
    - uses: actions/checkout@v2
    - name: Test Build
      run: |
        cd nameservice/nameservice && go get ./... && make install
