// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blog/sent_post.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SentPost struct {
	Id      uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostID  string `protobuf:"bytes,2,opt,name=postID,proto3" json:"postID,omitempty"`
	Title   string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Chain   string `protobuf:"bytes,4,opt,name=chain,proto3" json:"chain,omitempty"`
	Creator string `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *SentPost) Reset()         { *m = SentPost{} }
func (m *SentPost) String() string { return proto.CompactTextString(m) }
func (*SentPost) ProtoMessage()    {}
func (*SentPost) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba267cec3e3764dc, []int{0}
}
func (m *SentPost) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SentPost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SentPost.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SentPost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SentPost.Merge(m, src)
}
func (m *SentPost) XXX_Size() int {
	return m.Size()
}
func (m *SentPost) XXX_DiscardUnknown() {
	xxx_messageInfo_SentPost.DiscardUnknown(m)
}

var xxx_messageInfo_SentPost proto.InternalMessageInfo

func (m *SentPost) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SentPost) GetPostID() string {
	if m != nil {
		return m.PostID
	}
	return ""
}

func (m *SentPost) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SentPost) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *SentPost) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*SentPost)(nil), "cosmonaut.planet.blog.SentPost")
}

func init() { proto.RegisterFile("blog/sent_post.proto", fileDescriptor_ba267cec3e3764dc) }

var fileDescriptor_ba267cec3e3764dc = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8f, 0x31, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0xe3, 0xd0, 0x16, 0xf0, 0xc0, 0x60, 0x05, 0x64, 0x31, 0x58, 0x15, 0x53, 0xa6, 0x78,
	0xe0, 0x06, 0x15, 0x0b, 0x1b, 0x2a, 0x1b, 0x0b, 0x4a, 0x5c, 0xcb, 0xb5, 0x94, 0xfa, 0x59, 0xf1,
	0xab, 0x54, 0x6e, 0xc1, 0xb1, 0x18, 0x33, 0x32, 0xa2, 0xe4, 0x22, 0xc8, 0x36, 0x74, 0x7b, 0xdf,
	0xa7, 0x5f, 0x4f, 0xfa, 0x68, 0xd5, 0xf5, 0x60, 0x64, 0xd0, 0x0e, 0xdf, 0x3d, 0x04, 0x6c, 0xfc,
	0x00, 0x08, 0xec, 0x56, 0x41, 0x38, 0x80, 0x6b, 0x8f, 0xd8, 0xf8, 0xbe, 0x75, 0x1a, 0x9b, 0x38,
	0xbb, 0xaf, 0x0c, 0x18, 0x48, 0x0b, 0x19, 0xaf, 0x3c, 0x7e, 0x38, 0xd1, 0xab, 0x57, 0xed, 0xf0,
	0x05, 0x02, 0xb2, 0x1b, 0x5a, 0xda, 0x1d, 0x27, 0x6b, 0x52, 0x2f, 0xb6, 0xa5, 0xdd, 0xb1, 0x3b,
	0xba, 0x8a, 0x6f, 0x9f, 0x9f, 0x78, 0xb9, 0x26, 0xf5, 0xf5, 0xf6, 0x8f, 0x58, 0x45, 0x97, 0x68,
	0xb1, 0xd7, 0xfc, 0x22, 0xe9, 0x0c, 0xd1, 0xaa, 0x7d, 0x6b, 0x1d, 0x5f, 0x64, 0x9b, 0x80, 0x71,
	0x7a, 0xa9, 0x06, 0xdd, 0x22, 0x0c, 0x7c, 0x99, 0xfc, 0x3f, 0x6e, 0x36, 0x5f, 0x93, 0x20, 0xe3,
	0x24, 0xc8, 0xcf, 0x24, 0xc8, 0xe7, 0x2c, 0x8a, 0x71, 0x16, 0xc5, 0xf7, 0x2c, 0x8a, 0xb7, 0xda,
	0x58, 0xdc, 0x1f, 0xbb, 0x46, 0xc1, 0x41, 0x9e, 0x5b, 0x64, 0x6e, 0x91, 0x27, 0x99, 0xa2, 0xf1,
	0xc3, 0xeb, 0xd0, 0xad, 0x52, 0xc4, 0xe3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0x16, 0xf9,
	0x9b, 0x09, 0x01, 0x00, 0x00,
}

func (m *SentPost) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SentPost) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SentPost) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PostID) > 0 {
		i -= len(m.PostID)
		copy(dAtA[i:], m.PostID)
		i = encodeVarintSentPost(dAtA, i, uint64(len(m.PostID)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintSentPost(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintSentPost(dAtA []byte, offset int, v uint64) int {
	offset -= sovSentPost(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SentPost) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovSentPost(uint64(m.Id))
	}
	l = len(m.PostID)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovSentPost(uint64(l))
	}
	return n
}

func sovSentPost(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSentPost(x uint64) (n int) {
	return sovSentPost(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SentPost) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSentPost
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SentPost: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SentPost: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PostID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PostID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSentPost
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSentPost
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSentPost(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSentPost
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSentPost(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSentPost
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSentPost
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSentPost
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSentPost
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSentPost
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSentPost        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSentPost          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSentPost = fmt.Errorf("proto: unexpected end of group")
)
